<?php

namespace AfiliadosBundle\Repository;

/**
 * AfiliadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AfiliadosRepository extends \Doctrine\ORM\EntityRepository
{
}
